spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
auth:
  security:
    enabled: true
  expected-issuer: http://localhost:8080
  expected-audience: rumor
